// <auto-generated />
namespace QuanLyNha.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addpayment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpayment));
        
        string IMigrationMetadata.Id
        {
            get { return "202307281006511_add-payment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
